[config]
schemaVersion = "0.0.1"

[package]
namespace = "Poplinp"                # Change to your username
name = "Haha_No"
versionNumber = "1.0.0"
description = "Plays Poseidon voicelines on Sea Star failure."
websiteUrl = "https://github.com/shirimishor/HahaNo"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.70"   
LuaENVY-ENVY = "1.2.0"                 
SGG_Modding-ModUtil = "4.0.1" 
SGG_Modding-Chalk = "2.1.1"
SGG_Modding-ReLoad = "1.0.2"         

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii" ]

[publish.categories]
hades-ii = [ "mods" ]
